[package]
name = "tcp-test"
version = "0.1.0"
edition = "2021"

[features]
human_read_packet = []

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bytes = "1.5.0"
rand = "0.8.5"
base64 = "0.21.7"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"